FROM php:8.4-cli

RUN apt update && apt install -y zip unzip git libpq-dev && docker-php-ext-install pdo pdo_pgsql

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY beer-app/composer.json beer-app/composer.lock .

RUN composer install --no-scripts --no-autoloader

CMD php artisan serve --host=0.0.0.0 --port=8000
